version: 2

project_name: fleet

before:
  hooks:
    - make deps
    - make generate

# gomod:
#   proxy: true

builds:
  - id: fleet
    dir: ./cmd/fleet/
    binary: fleet
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -tags=full,fts5,netgo
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -X github.com/fleetdm/fleet/v4/server/version.appName={{ .ArtifactName }}
      - -X github.com/fleetdm/fleet/v4/server/version.version={{ .Version }}
      - -X github.com/fleetdm/fleet/v4/server/version.branch={{ .Branch }}
      - -X github.com/fleetdm/fleet/v4/server/version.revision={{ .FullCommit }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildDate={{ time "2006-01-02" }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildUser={{ .Env.USER }}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CGO_ENABLED=1
          - CC=aarch64-linux-gnu-gcc

archives:
  - id: fleet
    builds:
      - fleet
    name_template: fleet_v{{.Version}}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-untagged"

changelog:
  disable: true

release:
  # Disable goreleaser release - using softprops/action-gh-release instead
  disable: true
