version: 2

project_name: fleet

before:
  hooks:
    - make deps
    - make generate

# gomod:
#   proxy: true

builds:
  - id: fleet
    dir: ./cmd/fleet/
    binary: fleet
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    flags:
      - -tags=full,fts5,netgo
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -X github.com/fleetdm/fleet/v4/server/version.appName={{ .ArtifactName }}
      - -X github.com/fleetdm/fleet/v4/server/version.version={{ .Version }}
      - -X github.com/fleetdm/fleet/v4/server/version.branch={{ .Branch }}
      - -X github.com/fleetdm/fleet/v4/server/version.revision={{ .FullCommit }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildDate={{ time "2006-01-02" }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildUser={{ .Env.USER }}

  - id: fleetctl
    dir: ./cmd/fleetctl/
    binary: fleetctl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/fleetdm/fleet/v4/server/version.appName={{ .ArtifactName }}
      - -X github.com/fleetdm/fleet/v4/server/version.version={{ .Version }}
      - -X github.com/fleetdm/fleet/v4/server/version.branch={{ .Branch }}
      - -X github.com/fleetdm/fleet/v4/server/version.revision={{ .FullCommit }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildDate={{ time "2006-01-02" }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildUser={{ .Env.USER }}

  - id: fleetctl-macos
    dir: ./cmd/fleetctl/
    binary: fleetctl
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -X github.com/fleetdm/fleet/v4/server/version.appName={{ .ArtifactName }}
      - -X github.com/fleetdm/fleet/v4/server/version.version={{ .Version }}
      - -X github.com/fleetdm/fleet/v4/server/version.branch={{ .Branch }}
      - -X github.com/fleetdm/fleet/v4/server/version.revision={{ .FullCommit }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildDate={{ time "2006-01-02" }}
      - -X github.com/fleetdm/fleet/v4/server/version.buildUser={{ .Env.USER }}

archives:
  - id: fleet
    builds:
      - fleet
    name_template: fleet_v{{.Version}}_{{- if eq .Os "darwin" }}macos{{- else }}{{ .Os }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/fleet:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/fleet:v{{ .Major }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/fleet:latest"
    dockerfile: tools/fleet-docker/Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
    ids:
      - fleet
      - fleetctl
    extra_files:
      - tools/fleet-docker/entrypoint.sh
      - tools/fleet-docker/init-fleet.sh
      - tools/fleet-docker/fleet.yml

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-untagged"

changelog:
  disable: true

release:
  # Uses GITHUB_TOKEN to determine repository automatically
  draft: true
  prerelease: auto
